from __future__ import annotations

from datetime import datetime


def build_export(
    question: str,
    runs: list[dict],
    model: str,
    think: bool = False,
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    think_str = "enabled" if think else "disabled"

    lines: list[str] = [
        "# explaind Reasoning Chain",
        "",
        f"**Generated:** {now}  ",
        f"**Model:** {model}  ",
        f"**Thinking mode:** {think_str}  ",
        "",
        "---",
        "",
        "## Question",
        "",
        f"> {question}",
    ]

    for run in runs:
        ability = run.get("ability", "balanced")
        preset = run.get("preset")
        output = run.get("output", "")
        duration_ms = run.get("duration_ms")

        lines.append("")
        lines.append("---")
        lines.append("")

        if preset:
            lines.append(f"## Preset: {preset.title()}")
        else:
            lines.append(f"## Ability: {ability.title()}")

        lines.append("")
        lines.append(f"*Reasoning trajectory: {ability} · epistemic pressure applied*")
        lines.append("")
        lines.append(output)

        if duration_ms is not None:
            lines.append("")
            lines.append(f"*Inference time: {duration_ms}ms*")

    lines.extend([
        "",
        "---",
        "",
        "## Summary Notes",
        "",
        "*This section is intentionally blank — add your own synthesis, observations, or follow-up questions here.*",
        "",
        "---",
        "",
        "*Generated by [explaind](https://github.com/your/repo) — a cognitive steering layer for Gemma 4*",
        "",
    ])

    return "\n".join(lines)
