from __future__ import annotations

from datetime import datetime


def build_export(
    question: str,
    runs: list[dict],
    model: str,
    think: bool = False,
    scaffold_summary: str | None = None,
    consensus_report: dict | None = None,
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    think_str = "enabled" if think else "disabled"

    lines: list[str] = [
        "# explaind Reasoning Chain",
        "",
        f"**Generated:** {now}  ",
        f"**Model:** {model}  ",
        f"**Thinking mode:** {think_str}  ",
        "",
        "---",
        "",
        "## Question",
        "",
        f"> {question}",
    ]

    for run in runs:
        ability = run.get("ability", "balanced")
        preset = run.get("preset")
        output = run.get("output", "")
        duration_ms = run.get("duration_ms")

        lines.append("")
        lines.append("---")
        lines.append("")

        label = run.get("label")
        if label:
            lines.append(f"## {label}")
        elif preset:
            lines.append(f"## Preset: {preset.title()}")
        else:
            lines.append(f"## Ability: {ability.title()}")

        lines.append("")
        lines.append(f"*Reasoning trajectory: {ability} · epistemic pressure applied*")
        lines.append("")
        lines.append(output)

        if duration_ms is not None:
            lines.append("")
            lines.append(f"*Inference time: {duration_ms}ms*")

    if scaffold_summary:
        lines.extend([
            "",
            "---",
            "",
            scaffold_summary,
        ])

    if consensus_report is not None:
        n = consensus_report["n"]
        agreement = consensus_report["agreement"]
        pct = consensus_report["agreement_pct"]
        confidence = consensus_report["confidence"]
        divergent_runs = consensus_report["divergent_runs"]
        total_ms = consensus_report["total_ms"]
        lines.extend([
            "",
            "---",
            "",
            f"## Consensus Analysis ({n} runs)",
            "",
            f"**Agreement**: {agreement}/{n} runs ({pct:.0f}%)  ",
            f"**Confidence**: {confidence}  ",
            f"**Divergent runs**: {divergent_runs}  ",
            f"**Total inference time**: {total_ms}ms  ",
        ])

    lines.extend([
        "",
        "---",
        "",
        "## Summary Notes",
        "",
        "*This section is intentionally blank — add your own synthesis, observations, or follow-up questions here.*",
        "",
        "---",
        "",
        "*Generated by [explaind](https://github.com/your/repo) — a cognitive steering layer for Gemma 4*",
        "",
    ])

    return "\n".join(lines)


def build_demo_export(sections: list[dict], model: str, think: bool = False) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = [
        "# explaind Demo Output",
        "",
        "Three demonstrations of cognitive steering for Gemma 4.",
        f"Generated: {now}  ",
        f"Model: {model}  ",
        "",
        "---",
    ]

    for section in sections:
        title = section["title"]
        question = section["question"]
        runs = section.get("runs", [])

        lines.extend(["", f"## {title}", "", f"> {question}"])

        for r in runs:
            ability = r.get("ability", "balanced")
            label = r.get("label")
            output = r.get("output", "")
            duration_ms = r.get("duration_ms")

            lines.extend(["", "---", ""])
            lines.append(f"### {label}" if label else f"### {ability.title()}")
            lines.extend(["", output])
            if duration_ms is not None:
                lines.extend(["", f"*Inference time: {duration_ms}ms*"])

    lines.extend([
        "",
        "---",
        "",
        "*Generated by explaind — a cognitive steering layer for Gemma 4*",
        "",
    ])

    return "\n".join(lines)
